name: cat_printer_flutter_example
description: Demonstrates how to use the cat_printer_flutter plugin.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cat_printer_flutter:
    path: ../
  flutter_blue_plus: ^1.31.15
  permission_handler: ^11.3.0
  file_picker: ^6.1.1
  image: ^4.1.7
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true